server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Streamhu/spring-cloud-config/
          search-paths:
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

